services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development  # Set to 'production' in production
    depends_on:
      - mlflow

networks:
  default:
    driver: bridge